import { Client } from './types';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Ana Silva',
    phone: '(11) 99999-1111',
    email: 'ana@example.com',
    origin: 'WhatsApp',
    estimatedValue: 5000,
    notes: 'Cliente interessada em pacote premium',
    status: 'Novo Lead',
    createdAt: '2026-03-01',
  },
  {
    id: '2',
    name: 'Carlos Souza',
    phone: '(21) 98888-2222',
    email: 'carlos@example.com',
    origin: 'Instagram',
    estimatedValue: 12000,
    notes: 'Quer fechar em marco',
    status: 'Em Contato',
    createdAt: '2026-02-20',
  },
  {
    id: '3',
    name: 'Beatriz Lima',
    phone: '(85) 97777-3333',
    email: 'beatriz@example.com',
    origin: 'Indicacao',
    estimatedValue: 8500,
    notes: 'Indicada pela Ana Silva',
    status: 'Proposta Enviada',
    createdAt: '2026-02-15',
  },
  {
    id: '4',
    name: 'Roberto Nunes',
    phone: '(31) 96666-4444',
    email: 'roberto@example.com',
    origin: 'Site',
    estimatedValue: 22000,
    notes: 'Contrato assinado',
    status: 'Fechado',
    createdAt: '2026-01-10',
  },
  {
    id: '5',
    name: 'Mariana Costa',
    phone: '(71) 95555-5555',
    email: 'mariana@example.com',
    origin: 'WhatsApp',
    estimatedValue: 3000,
    notes: 'Orcamento fora do budget',
    status: 'Perdido',
    createdAt: '2026-01-25',
  },
];
